name: roomia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  image_picker: ^1.1.1

  # Core Dependencies
  get: ^4.6.6
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding_images/
    - assets/login_signup_images/
    - assets/hostels/
